-- Run this in the Supabase SQL editor to create the topic_requests table.

create table if not exists public.topic_requests (
  id                uuid primary key default gen_random_uuid(),
  viewer_name       text,
  message           text not null,
  base_amount       integer not null default 500,   -- cents
  tip_amount        integer not null default 0,     -- cents
  priority_score    float   not null default 0,     -- higher = processed first
  stripe_session_id text,
  status            text not null default 'pending', -- pending | processing | done | skipped | error
  agent_setup       jsonb,                           -- whiteboard + members generated by setup agent
  created_at        timestamptz not null default now(),
  started_at        timestamptz,
  ended_at          timestamptz
);

-- Index for the queue poll query (status + priority + time)
create index if not exists topic_requests_queue_idx
  on public.topic_requests (status, priority_score desc, created_at asc);

-- RLS: the server uses the service role key so no RLS policies needed,
-- but enable RLS to block anonymous browser access.
alter table public.topic_requests enable row level security;

-- (Optional) allow authenticated users to see their own requests by session ID
-- create policy "viewer can see own request"
--   on public.topic_requests for select
--   using (true);  -- adjust if you add auth to the viewer page
